services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coaching
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_DATA_DIR:-./mysql_data}:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    environment:
      DB_DSN: "root:password@tcp(db:3306)/coaching?charset=utf8mb4&parseTime=True&loc=Local"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"